

GrayScott_ETDRK4.pdf: GrayScott_ETDRK4.tex biblio.bib
	pdflatex GrayScott_ETDRK4.tex
	bibtex GrayScott_ETDRK4
	pdflatex GrayScott_ETDRK4.tex
	pdflatex GrayScott_ETDRK4.tex

clean:
	rm *~ *.aux *.log *.out *.bbl *.blg -f
